require('dotenv').config();
const mongoose = require('mongoose');
const Template = require('../src/models/Template');

const premadeTemplates = [
  {
    name: 'Contact Form',
    description: 'Simple contact form with name, email, and message fields',
    category: 'contact',
    isPremade: true,
    thumbnail: '📧',
    fields: [
      {
        type: 'short_text',
        label: 'Full Name',
        placeholder: 'Enter your full name',
        required: true,
        order: 0,
        width: 'full',
      },
      {
        type: 'email',
        label: 'Email Address',
        placeholder: 'your@email.com',
        required: true,
        order: 1,
        width: 'full',
      },
      {
        type: 'short_text',
        label: 'Subject',
        placeholder: 'What is this about?',
        required: false,
        order: 2,
        width: 'full',
      },
      {
        type: 'long_text',
        label: 'Message',
        placeholder: 'Type your message here...',
        required: true,
        order: 3,
        width: 'full',
      },
    ],
    settings: {
      allowMultipleSubmissions: true,
      requireLogin: false,
      notifyOnSubmit: true,
      customMessage: 'Thank you for contacting us! We will get back to you soon.',
    },
  },
  {
    name: 'Customer Feedback Survey',
    description: 'Collect customer satisfaction ratings and feedback',
    category: 'feedback',
    isPremade: true,
    thumbnail: '⭐',
    fields: [
      {
        type: 'short_text',
        label: 'Your Name',
        placeholder: 'Enter your name',
        required: true,
        order: 0,
        width: 'half',
      },
      {
        type: 'email',
        label: 'Email',
        placeholder: 'your@email.com',
        required: true,
        order: 1,
        width: 'half',
      },
      {
        type: 'rating',
        label: 'Overall Satisfaction',
        placeholder: 'Rate your experience',
        required: true,
        order: 2,
        width: 'full',
      },
      {
        type: 'radio',
        label: 'Would you recommend us?',
        options: ['Definitely', 'Probably', 'Not sure', 'Probably not', 'Definitely not'],
        required: true,
        order: 3,
        width: 'full',
      },
      {
        type: 'long_text',
        label: 'Additional Comments',
        placeholder: 'Share your thoughts...',
        required: false,
        order: 4,
        width: 'full',
      },
    ],
    settings: {
      allowMultipleSubmissions: false,
      requireLogin: false,
      notifyOnSubmit: true,
      customMessage: 'Thank you for your feedback!',
    },
  },
  {
    name: 'Event Registration',
    description: 'Complete event registration form with attendee details',
    category: 'registration',
    isPremade: true,
    thumbnail: '🎟️',
    fields: [
      {
        type: 'short_text',
        label: 'Full Name',
        placeholder: 'Enter your full name',
        required: true,
        order: 0,
        width: 'full',
      },
      {
        type: 'email',
        label: 'Email Address',
        placeholder: 'your@email.com',
        required: true,
        order: 1,
        width: 'half',
      },
      {
        type: 'short_text',
        label: 'Phone Number',
        placeholder: '+1234567890',
        required: true,
        order: 2,
        width: 'half',
      },
      {
        type: 'short_text',
        label: 'Company/Organization',
        placeholder: 'Your organization',
        required: false,
        order: 3,
        width: 'full',
      },
      {
        type: 'dropdown',
        label: 'Ticket Type',
        options: ['Early Bird', 'Regular', 'VIP', 'Student'],
        required: true,
        order: 4,
        width: 'half',
      },
      {
        type: 'number',
        label: 'Number of Attendees',
        placeholder: '1',
        required: true,
        order: 5,
        width: 'half',
      },
      {
        type: 'checkbox',
        label: 'Dietary Requirements',
        options: ['Vegetarian', 'Vegan', 'Gluten-free', 'Dairy-free', 'None'],
        required: false,
        order: 6,
        width: 'full',
      },
      {
        type: 'long_text',
        label: 'Special Requirements',
        placeholder: 'Any special accommodations needed?',
        required: false,
        order: 7,
        width: 'full',
      },
    ],
    settings: {
      allowMultipleSubmissions: false,
      requireLogin: false,
      notifyOnSubmit: true,
      customMessage: 'Registration successful! Check your email for confirmation.',
    },
  },
  {
    name: 'Job Application',
    description: 'Comprehensive job application form',
    category: 'registration',
    isPremade: true,
    thumbnail: '💼',
    fields: [
      {
        type: 'short_text',
        label: 'Full Name',
        placeholder: 'Enter your full name',
        required: true,
        order: 0,
        width: 'full',
      },
      {
        type: 'email',
        label: 'Email',
        placeholder: 'your@email.com',
        required: true,
        order: 1,
        width: 'half',
      },
      {
        type: 'short_text',
        label: 'Phone',
        placeholder: '+1234567890',
        required: true,
        order: 2,
        width: 'half',
      },
      {
        type: 'dropdown',
        label: 'Position Applied For',
        options: ['Software Engineer', 'Designer', 'Product Manager', 'Marketing', 'Sales', 'Other'],
        required: true,
        order: 3,
        width: 'full',
      },
      {
        type: 'short_text',
        label: 'Current Company',
        placeholder: 'Your current employer',
        required: false,
        order: 4,
        width: 'full',
      },
      {
        type: 'number',
        label: 'Years of Experience',
        placeholder: '0',
        required: true,
        order: 5,
        width: 'half',
      },
      {
        type: 'short_text',
        label: 'Expected Salary',
        placeholder: '$XXX,XXX',
        required: false,
        order: 6,
        width: 'half',
      },
      {
        type: 'file',
        label: 'Resume/CV',
        placeholder: 'Upload your resume',
        required: true,
        order: 7,
        width: 'full',
      },
      {
        type: 'long_text',
        label: 'Cover Letter',
        placeholder: 'Tell us why you want to join...',
        required: false,
        order: 8,
        width: 'full',
      },
    ],
    settings: {
      allowMultipleSubmissions: false,
      requireLogin: false,
      notifyOnSubmit: true,
      customMessage: 'Application submitted! We will review and get back to you.',
    },
  },
  {
    name: 'Quick Survey',
    description: 'Simple multi-choice survey template',
    category: 'survey',
    isPremade: true,
    thumbnail: '📊',
    fields: [
      {
        type: 'short_text',
        label: 'Your Name (Optional)',
        placeholder: 'Enter your name',
        required: false,
        order: 0,
        width: 'full',
      },
      {
        type: 'radio',
        label: 'How did you hear about us?',
        options: ['Social Media', 'Search Engine', 'Friend Referral', 'Advertisement', 'Other'],
        required: true,
        order: 1,
        width: 'full',
      },
      {
        type: 'checkbox',
        label: 'Which features interest you?',
        options: ['Feature A', 'Feature B', 'Feature C', 'Feature D'],
        required: true,
        order: 2,
        width: 'full',
      },
      {
        type: 'rating',
        label: 'Rate your experience',
        placeholder: 'Select rating',
        required: true,
        order: 3,
        width: 'full',
      },
      {
        type: 'long_text',
        label: 'Any suggestions?',
        placeholder: 'We appreciate your feedback...',
        required: false,
        order: 4,
        width: 'full',
      },
    ],
    settings: {
      allowMultipleSubmissions: false,
      requireLogin: false,
      notifyOnSubmit: false,
      customMessage: 'Thank you for completing our survey!',
    },
  },
  {
    name: 'Product Template',
    description: 'Product order form with customer and product details',
    category: 'product',
    isPremade: true,
    thumbnail: '🛍️',
    fields: [
      {
        type: 'short_text',
        label: 'Product Name',
        placeholder: 'Enter product name',
        required: true,
        order: 0,
        width: 'full',
      },
      {
        type: 'short_text',
        label: 'Product Category',
        placeholder: 'Enter product category',
        required: true,
        order: 1,
        width: 'half',
      },
      {
        type: 'number',
        label: 'Quantity',
        placeholder: '1',
        required: true,
        order: 2,
        width: 'half',
      },
      {
        type: 'short_text',
        label: 'Price',
        placeholder: '$0.00',
        required: true,
        order: 3,
        width: 'full',
      },
      {
        type: 'short_text',
        label: 'Customer Name',
        placeholder: 'Enter customer name',
        required: true,
        order: 4,
        width: 'half',
      },
      {
        type: 'email',
        label: 'Email',
        placeholder: 'customer@email.com',
        required: true,
        order: 5,
        width: 'half',
      },
    ],
    settings: {
      allowMultipleSubmissions: true,
      requireLogin: false,
      notifyOnSubmit: true,
      customMessage: 'Thank you for your product order!',
    },
  },
  {
    name: 'Course Template',
    description: 'Collect course enrollment details from students',
    category: 'education',
    isPremade: true,
    thumbnail: '🎓',
    fields: [
      {
        type: 'short_text',
        label: 'Course Name',
        placeholder: 'Enter course name',
        required: true,
        order: 0,
        width: 'full',
      },
      {
        type: 'short_text',
        label: 'Student Name',
        placeholder: 'Enter student name',
        required: true,
        order: 1,
        width: 'half',
      },
      {
        type: 'email',
        label: 'Email',
        placeholder: 'student@email.com',
        required: true,
        order: 2,
        width: 'half',
      },
      {
        type: 'dropdown',
        label: 'Mode',
        options: ['Online', 'Offline', 'Hybrid'],
        required: true,
        order: 3,
        width: 'full',
      },
    ],
    settings: {
      allowMultipleSubmissions: true,
      requireLogin: false,
      notifyOnSubmit: true,
      customMessage: 'Enrollment submitted successfully!',
    },
  },
  {
    name: 'Trip Package',
    description: 'Capture trip package details and traveler info',
    category: 'travel',
    isPremade: true,
    thumbnail: '🧳',
    metadata: [
      {
        label: 'Destination',
        value: '',
      },
      {
        label: 'Duration',
        value: '',
      },
      {
        label: 'Price',
        value: '',
      },
      {
        label: 'Itinerary',
        value: '',
      },
    ],
    fields: [
      {
        type: 'dropdown',
        label: 'Package Type',
        options: ['Standard', 'Deluxe', 'Premium', 'Custom'],
        required: true,
        order: 1,
        width: 'half',
      },
      {
        type: 'date',
        label: 'Travel Date',
        placeholder: 'Select date',
        required: true,
        order: 2,
        width: 'half',
      },
      {
        type: 'number',
        label: 'Travelers',
        placeholder: '1',
        required: true,
        order: 3,
        width: 'half',
      },
      {
        type: 'short_text',
        label: 'Name',
        placeholder: 'Enter primary traveler name',
        required: true,
        order: 4,
        width: 'half',
      },
      {
        type: 'email',
        label: 'Email',
        placeholder: 'traveler@email.com',
        required: true,
        order: 5,
        width: 'half',
      },
    ],
    settings: {
      allowMultipleSubmissions: true,
      requireLogin: false,
      notifyOnSubmit: true,
      customMessage: 'Trip request submitted successfully!',
    },
  },
  {
    name: 'Appointment Booking Template',
    description: 'Book appointments with preferred service and time slot',
    category: 'appointment',
    isPremade: true,
    thumbnail: '📅',
    metadata: [
      {
        label: 'Appointment Title',
        value: '',
      },
      {
        label: 'Appointment Type',
        value: '',
      },
      {
        label: 'Appointment Date & Time',
        value: '',
      },
      {
        label: 'Location',
        value: '',
      },
      {
        label: 'Description',
        value: '',
      },
    ],
    fields: [
      {
        type: 'short_text',
        label: 'Appointment Title',
        placeholder: 'Enter the title for the appointment',
        required: true,
        order: 0,
        width: 'full',
      },
      {
        type: 'dropdown',
        label: 'Appointment Type',
        options: ['Consultation', 'Check-up', 'Follow-up', 'New Patient', 'Other'],
        required: true,
        order: 1,
        width: 'full',
      },
      {
        type: 'date',
        label: 'Preferred Date',
        placeholder: 'Select a date',
        required: true,
        order: 2,
        width: 'half',
      },
      {
        type: 'short_text',
        label: 'Preferred Time',
        placeholder: 'e.g., 10:00 AM',
        required: true,
        order: 3,
        width: 'half',
      },
      {
        type: 'short_text',
        label: 'Location',
        placeholder: 'Enter the location',
        required: false,
        order: 4,
        width: 'full',
      },
      {
        type: 'long_text',
        label: 'Description',
        placeholder: 'Provide a brief description of the appointment',
        required: false,
        order: 5,
        width: 'full',
      },
      {
        type: 'short_text',
        label: 'Name',
        placeholder: 'Enter your name',
        required: true,
        order: 6,
        width: 'half',
      },
      {
        type: 'email',
        label: 'Email',
        placeholder: 'your@email.com',
        required: true,
        order: 7,
        width: 'half',
      },
      {
        type: 'short_text',
        label: 'Phone',
        placeholder: '+1 (555) 123-4567',
        required: true,
        order: 8,
        width: 'full',
      },
    ],
    settings: {
      allowMultipleSubmissions: true,
      requireLogin: false,
      notifyOnSubmit: true,
      customMessage: 'Appointment booked successfully!',
    },
  },
  {
    name: 'Event RSVP',
    description: 'RSVP for an event',
    category: 'event',
    isPremade: true,
    thumbnail: '🗓️',
    fields: [
      {
        type: 'short_text',
        label: 'Full Name',
        placeholder: 'Enter your full name',
        required: true,
        order: 0,
        width: 'full',
      },
      {
        type: 'email',
        label: 'Email Address',
        placeholder: 'your@email.com',
        required: true,
        order: 1,
        width: 'full',
      },
      {
        type: 'dropdown',
        label: 'Event Status',
        options: ['Going', 'Not Going', 'Maybe'],
        required: true,
        order: 2,
        width: 'full',
      },
      {
        type: 'number',
        label: 'Capacity',
        placeholder: '0',
        required: true,
        order: 3,
        width: 'full',
      },
      {
        type: 'long_text',
        label: 'Agenda',
        placeholder: 'What is the event agenda?',
        required: false,
        order: 4,
        width: 'full',
      },
    ],
    settings: {
      allowMultipleSubmissions: false,
      requireLogin: false,
      notifyOnSubmit: true,
      customMessage: 'Thank you for your RSVP!',
    },
  },
];

async function seedTemplates() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB connected...');

    // Clear existing premade templates
    await Template.deleteMany({ isPremade: true });
    console.log('Cleared existing premade templates');

    // Insert new templates
    await Template.insertMany(premadeTemplates);
    console.log(`✅ Successfully seeded ${premadeTemplates.length} premade templates`);

    process.exit(0);
  } catch (error) {
    console.error('Error seeding templates:', error);
    process.exit(1);
  }
}

seedTemplates();